# Don't edit this file
#
# It was auto generated by CMake from module.json which should be edited instead

set(DEPENDENT_NAP_MODULES napwarp napparameter)
set(DEEP_DEPENDENT_NAP_MODULES napwarp napparameter naprenderadvanced napopencv napscene napcolor naprender napmath napfont napinput)
set(DEEP_DEPENDENT_RPATHS ../../../../modules/napopencv/thirdparty/opencv/linux/x86_64/lib ../../../../system_modules/napvideo/thirdparty/ffmpeg/linux/x86_64/lib ../../../../system_modules/naprender/thirdparty/assimp/linux/x86_64/lib ../../../../system_modules/naprender/thirdparty/FreeImage/linux/x86_64/lib ../../../../system_modules/naprender/thirdparty/vulkansdk/linux/x86_64/lib ../../../../system_modules/naprender/thirdparty/SDL2/linux/x86_64/lib ../../../../system_modules/napfont/thirdparty/freetype/linux/x86_64/lib)
